
[ClassVersion("1.0.0.0"), FriendlyName("SChannelSettings")]
class MSFT_SChannelSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies the state of TLS 1.2 for the .Net Framework 3.5 and 4.*"), ValueMap{"Enabled","Disabled","Default"}, Values{"Enabled","Disabled","Default"}] String TLS12State;
    [Write, Description("Minimum client key size for the Diffie-Hellman key exchange algorithm"), ValueMap{"1024","2048","3072","4096"}, Values{"1024","2048","3072","4096"}] Uint32 DiffieHellmanMinClientKeySize;
    [Write, Description("Minimum server key size for the Diffie-Hellman key exchange algorithm"), ValueMap{"1024","2048","3072","4096"}, Values{"1024","2048","3072","4096"}] Uint32 DiffieHellmanMinServerKeySize;
    [Write, Description("Specifies the supported Kerberos Encryption Types"), ValueMap{"DES-CBC-CRC","DES-CBC-MD5","RC4-HMAC-MD5","AES128-HMAC-SHA1","AES256-HMAC-SHA1"}, Values{"DES-CBC-CRC","DES-CBC-MD5","RC4-HMAC-MD5","AES128-HMAC-SHA1","AES256-HMAC-SHA1"}] String KerberosSupportedEncryptionType[];
    [Write, Description("Specifies the WinHTTP Default Secure Protocols"), ValueMap{"SSL2.0","SSL3.0","TLS1.0","TLS1.1","TLS1.2"}, Values{"SSL2.0","SSL3.0","TLS1.0","TLS1.1","TLS1.2"}] String WinHttpDefaultSecureProtocols[];
    [Write, Description("Specifies if the FIPS Algorithm Policy is enabled")] Boolean EnableFIPSAlgorithmPolicy;
};
