
[ClassVersion("1.0.0.0"), FriendlyName("CipherSuites")]
class MSFT_CipherSuites : OMI_BaseResource
{
    [Write] String CipherSuitesOrder[];
    [Key, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

