
[ClassVersion("1.0.0.0"), FriendlyName("Cipher")]
class MSFT_Cipher : OMI_BaseResource
{
    [Key, Description("Specifies the Cipher to configure"), ValueMap{"AES 128/128","AES 256/256","DES 56/56","NULL","RC2 128/128","RC2 40/128","RC2 56/128","RC4 128/128","RC4 40/128","RC4 56/128","RC4 64/128","Triple DES 168"}, Values{"AES 128/128","AES 256/256","DES 56/56","NULL","RC2 128/128","RC2 40/128","RC2 56/128","RC4 128/128","RC4 40/128","RC4 56/128","RC4 64/128","Triple DES 168"}] String Cipher;
    [Write, Description("Specifies the state of the Cipher"), ValueMap{"Enabled","Disabled","Default"}, Values{"Enabled","Disabled","Default"}] String State;
    [Write, Description("Specifies if a reboot will be performed when required (Default: False)")] Boolean RebootWhenRequired;
};
